# Generated by Django 3.1.5 on 2021-02-02 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booksApp', '0007_auto_20210202_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='client',
            field=models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='booksApp.client'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='librarian',
            field=models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='librarians', to='booksApp.librarian'),
        ),
    ]
